version: '3.3'

services:
  db:
    image: mysql:8.0.4
    restart: always
    environment:
      MYSQL_DATABASE: 'db_test'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - foodiepie:/var/lib/mysql
volumes:
  foodiepie:
