version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      TYPEORM_USERNAME: 'root'
      TYPEORM_PASSWORD: 'password'
      TYPEORM_DATABASE: 'db_test'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - foodiepie:/var/lib/postgresql/data
volumes:
  foodiepie:
