version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db_test'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - foodiepie:/var/lib/postgresql/data
volumes:
  foodiepie:
