version: '3' # 3.8

services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      TYPEORM_USERNAME: 'root'
      TYPEORM_PASSWORD: 'password'
      TYPEORM_DATABASE: 'db_test'
      TYPEORM_HOST: 'postgres'
      PORT: '4000'
      JWT_CONFIG_SECRET: 'XXX'
    ports:
      - '4000:4000'
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db_test'
    ports:
      - '35432:5432'
    expose:
      - '5432'
    volumes:
      - posgres-data:/var/lib/postgresql/data
volumes:
  posgres-data:
