version: 2.1
orbs:
  node: circleci/node@1.1.6

executors:
  node-db:
    docker:
      - image: circleci/mysql:latest
      - image: circleci/node:latest
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: db_test
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

commands:
  init-db:
    steps:
      - run: sudo apt-get install default-mysql-client
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm i

  unit-test:
    executor:
      name: node-db
    steps:
      - checkout
      - node/with-cache:
          steps:
            # temp with db conn. later will be moved to e2e.
            - init-db
            - run: npm test

workflows:
  # version: 2.1
  build-and-test:
    jobs:
      - build

      - unit-test:
          requires:
            - build
