import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { INestApplication } from '@nestjs/common';

const conf = {
  title: 'FoodiePie API',
  description: 'Food Delivery Application',
  version: '0.0.1',
  path: 'api-docs',
  auth: {
    description:
      "For accessing the protected API resources, you must have received a a valid JWT token after registering or logging in. This JWT token must then be used for all protected resources by passing it in via the 'Authorization' header.\n\nA JWT token is generated by the API by either registering via /users or logging in via /users/login.\n\nThe following format must be in the 'Authorization' header :\n\n    Token: xxxxxx.yyyyyyy.zzzzzz\n    \n",
  },
};

export function add(app: INestApplication): void {
  const options = new DocumentBuilder()
    .setTitle(conf.title)
    .setDescription(conf.description)
    .setVersion(conf.version)
    .addBearerAuth({
      type: 'apiKey',
      in: 'header',
      name: 'Authorization',
      description: conf.auth.description,
    })
    .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup(conf.path, app, document);
}
